chore(approve)
FiveElementsLabs/orbit-defi pull request #108
Opened 2022-05-30 09:15 UTC by AlbyGiaco

2022-05-30 10:41 UTC, RiccardoGalbusera requested changes

2022-05-30 10:41 UTC, RiccardoGalbusera commented on contracts/actions/AaveDeposit.sol
> +        if (IERC20(token).allowance(address(this), address(lendingPool)) == 0) {
And if by chance this allowance isn't 0? Please add an else statement (or use approve(0) -> approve(amount) pattern)

2022-05-31 10:26 UTC, luduvigo requested changes

2022-05-31 10:26 UTC, luduvigo commented on contracts/actions/AaveDeposit.sol
> +            IERC20(token).approve(address(lendingPool), 0);
Let's approve 0 at the beginning of the **depositToAave** and not in diff

2022-05-31 10:26 UTC, luduvigo commented on contracts/actions/AaveDeposit.sol
> +            IERC20(token).approve(address(lendingPool), 2**256 - 1);
What are we approving here?
Are we sure about this?

2022-05-31 13:30 UTC, nicolas-racchi approved these changes

2022-05-31 14:16 UTC, RiccardoGalbusera approved these changes

2022-05-31 14:16 UTC, merged