ORB 538 - Add safemath for int24 in idleLiquidity module
FiveElementsLabs/orbit-defi pull request #109
Opened 2022-05-30 13:10 UTC by RiccardoGalbusera

2022-05-30 13:22 UTC, AlbyGiaco commented
Add SafeMath in others tickOperation like in AaveModule

2022-05-31 10:50 UTC, luduvigo requested changes

2022-05-31 10:50 UTC, luduvigo commented on contracts/modules/AaveModule.sol
> +            return uint24(tick.sub(tickUpper));
Please, let's review the overflows/underflows here

2022-05-31 12:39 UTC, luduvigo approved these changes

2022-05-31 12:39 UTC, merged