PositionManagerFactory - UpdateActionsData
FiveElementsLabs/orbit-defi pull request #155
Opened 2022-07-14 12:32 UTC by RiccardoGalbusera

2022-07-14 12:37 UTC, AlbyGiaco requested changes

2022-07-14 12:37 UTC, AlbyGiaco commented on contracts/PositionManagerFactory.sol
> +                uint256 newSelectorsLength = facetAction.functionSelectors.length;
outside for loop, gas wasting

2022-07-14 12:37 UTC, AlbyGiaco commented on contracts/PositionManagerFactory.sol
> +                            different = true;
use break to not cycle anymore for gas saving

2022-07-14 12:37 UTC, AlbyGiaco commented on contracts/PositionManagerFactory.sol
> +                    bool different = false;
do not initialize default value

2022-07-15 10:32 UTC, luduvigo approved these changes

2022-07-15 10:35 UTC, merged