Bd 352 - Factory Contract (without timelock functionalities)
FiveElementsLabs/orbit-defi pull request #60
Opened 2022-04-12 13:58 UTC by RiccardoGalbusera

tests follow the structure implemented with diamond pattern implementation, so, even if there are no conflicts, tests may be broken until we merge that pr

2022-04-12 15:39 UTC, RiccardoGalbusera commented
Updated with diamond pattern merge!

2022-04-12 15:50 UTC, nicolas-racchi approved these changes

2022-04-13 08:02 UTC, luduvigo requested changes

2022-04-13 08:02 UTC, luduvigo commented on test/Registry.spec.ts
> +  let IdleLiquidityModule: Contract;
Can we use the same naming convention here? capitalized - non-capitalized

2022-04-13 08:02 UTC, luduvigo commented on contracts/Registry.sol
> +    function toggleModule(bytes32 _id, bool _activated) external onlyGovernance {
Let's improve the name of this function

2022-04-13 08:06 UTC, RiccardoGalbusera commented on contracts/Registry.sol
> +    function toggleModule(bytes32 _id, bool _activated) external onlyGovernance {
renamed as swichModuleState

2022-04-13 08:06 UTC, AlbyGiaco commented on test/Registry.spec.ts
>    describe('Deployment ', function () {
Change to the name of contract

2022-04-13 08:07 UTC, AlbyGiaco commented on test/Registry.spec.ts
>    describe('Modules update ', function () {
This too, change with the name of "Contract.sol - Function"

2022-04-13 08:07 UTC, AlbyGiaco commented on test/Registry.spec.ts
>    describe('Deployment ', function () {
"Contract.sol - Function"

2022-04-13 09:01 UTC, luduvigo approved these changes

2022-04-13 09:01 UTC, merged