Modifier
FiveElementsLabs/orbit-defi pull request #87
Opened 2022-04-27 15:05 UTC by AlbyGiaco

feat(modifier): adding modifier to position manager, onlyOwner, onlyGov, and make actions add remove replace only by gov

2022-04-27 15:06 UTC, AlbyGiaco commented on contracts/Registry.sol
> +    address public override keeper;
@SBfin https://bridgedefi.atlassian.net/browse/ORB-349?atlOrigin=eyJpIjoiYmE2YzY5MDg0NzM2NDQzMWI0MmI2Yjk2NzNmY2FiZjAiLCJwIjoiaiJ9

2022-04-27 15:39 UTC, RiccardoGalbusera approved these changes

2022-04-27 15:39 UTC, RiccardoGalbusera commented on contracts/PositionManagerFactory.sol
> +        address _governance
Isn't it better if we fetch governance somewhere? For example registry

2022-04-27 15:39 UTC, RiccardoGalbusera commented on contracts/utils/Storage.sol
> +    address governance;
maybe put the two addresses togheter for clarity purposes?

2022-04-27 15:39 UTC, RiccardoGalbusera commented on contracts/utils/Storage.sol
> +        require(msg.sender == ds.governance, 'LibDiamond: Must be contract owner');
'Contract::function: error message'

2022-04-28 07:46 UTC, nicolas-racchi approved these changes

2022-04-28 15:01 UTC, luduvigo requested changes

2022-04-29 09:35 UTC, luduvigo approved these changes

2022-04-29 09:35 UTC, merged